# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=500)),
                ('p_category', models.CharField(max_length=250)),
                ('p_level', models.CharField(max_length=100)),
                ('p_users_needed', models.IntegerField()),
                ('p_status', models.CharField(max_length=200)),
                ('p_description', models.CharField(max_length=5000)),
                ('p_privacy', models.BooleanField(default=False)),
                ('p_post_date', models.DateField(max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_fname', models.CharField(max_length=50)),
                ('u_lname', models.CharField(max_length=50)),
                ('u_name', models.CharField(max_length=100)),
                ('u_password', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=500)),
                ('u_gender', models.CharField(max_length=10)),
                ('u_dob', models.DateField(max_length=20)),
                ('u_github', models.CharField(max_length=500)),
                ('u_linkedin', models.CharField(max_length=500)),
                ('u_contact_no', models.CharField(max_length=50)),
                ('u_prof_title', models.CharField(max_length=500)),
                ('u_mentor', models.BooleanField(default=False)),
                ('u_location', models.CharField(max_length=1000)),
                ('u_bio', models.CharField(max_length=5000)),
                ('u_current_qualification', models.CharField(max_length=500, null=True)),
                ('u_current_degree', models.CharField(max_length=500)),
                ('u_current_college', models.CharField(max_length=1000)),
                ('u_education_start_year', models.DateField(max_length=20)),
                ('u_education_end_year', models.DateField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_project', to='mainapp.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to='mainapp.User'),
        ),
    ]
