# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20161025_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
