# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_auto_20161026_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=20)),
                ('p_category', models.CharField(max_length=50)),
                ('diff_level', models.CharField(max_length=10)),
                ('no_of_contrib', models.PositiveIntegerField()),
                ('p_status', models.CharField(max_length=100)),
                ('p_description', models.TextField(max_length=200)),
                ('p_privacy', models.BooleanField(default=False)),
                ('post_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
