# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Project')),
            ],
        ),
    ]
