# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_project_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Skills',
            new_name='ProjectSkills',
        ),
    ]
