# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20161029_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectskills',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Project'),
        ),
    ]
