# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_auto_20161029_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_github', models.CharField(max_length=500)),
                ('u_linkedin', models.CharField(max_length=500)),
                ('u_contact_no', models.CharField(blank=True, default='', max_length=50)),
                ('u_prof_title', models.CharField(max_length=500)),
                ('u_location', models.CharField(max_length=1000)),
                ('u_bio', models.TextField(blank=True, default='', max_length=2000)),
                ('u_current_qualification', models.CharField(max_length=500)),
                ('u_current_degree', models.CharField(max_length=500)),
                ('u_current_college', models.CharField(max_length=1000)),
                ('u_education_start_year', models.DateField(max_length=20)),
                ('u_education_end_year', models.DateField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
