# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20161105_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='p_location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
