# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 17:15
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20161105_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectskills',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java')], default='python', max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectSkills',
        ),
    ]
