# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 18:03
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20161118_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java')], max_length=6000),
        ),
    ]
