# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20161118_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java')], default='python', max_length=6000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='diff_level',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_category',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_title',
            field=models.CharField(max_length=200),
        ),
    ]
