# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_project_p_location'),
        ('mainapp', '0021_auto_20161118_1934'),
    ]

    operations = [
    ]
