# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_merge_20161118_2001'),
        ('mainapp', '0022_merge_20161118_2022'),
    ]

    operations = [
    ]
