# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 04:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_merge_20161118_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('bootstrap', 'Bootstrap'), ('php', 'PHP'), ('mySql', 'MySql')], max_length=6000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('bootstrap', 'Bootstrap'), ('php', 'PHP'), ('mySql', 'MySql')], max_length=6000),
        ),
    ]
