# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20161119_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='p_category',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_description',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_location',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_privacy',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_title',
            field=models.CharField(max_length=2000),
        ),
    ]
