# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20161119_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='u_contact_no',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
